
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("2fec72c8-914b-411a-b2f7-794fba9995dd")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("Model", "CategoriaProduto", "Categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Categoria), "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Produto), True)>
<Assembly: EdmRelationshipAttribute("Model", "ProdutoProdutoCor", "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Produto), "ProdutoCor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ProdutoCor), True)>
<Assembly: EdmRelationshipAttribute("Model", "ProdutoCorProdutoTamanho", "ProdutoCor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(ProdutoCor), "ProdutoTamanho", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ProdutoTamanho), True)>
<Assembly: EdmRelationshipAttribute("Model", "CorProdutoCor", "Cor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Cor), "ProdutoCor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ProdutoCor), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class Entities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=Entities", "Entities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Entities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Entities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Entities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "Entities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property CategoriaSet() As ObjectSet(Of Categoria)
        Get
            If (_CategoriaSet Is Nothing) Then
                _CategoriaSet = MyBase.CreateObjectSet(Of Categoria)("CategoriaSet")
            End If
            Return _CategoriaSet
        End Get
    End Property

    Private _CategoriaSet As ObjectSet(Of Categoria)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ProdutoSet() As ObjectSet(Of Produto)
        Get
            If (_ProdutoSet Is Nothing) Then
                _ProdutoSet = MyBase.CreateObjectSet(Of Produto)("ProdutoSet")
            End If
            Return _ProdutoSet
        End Get
    End Property

    Private _ProdutoSet As ObjectSet(Of Produto)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ProdutoCorSet() As ObjectSet(Of ProdutoCor)
        Get
            If (_ProdutoCorSet Is Nothing) Then
                _ProdutoCorSet = MyBase.CreateObjectSet(Of ProdutoCor)("ProdutoCorSet")
            End If
            Return _ProdutoCorSet
        End Get
    End Property

    Private _ProdutoCorSet As ObjectSet(Of ProdutoCor)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property CorSet() As ObjectSet(Of Cor)
        Get
            If (_CorSet Is Nothing) Then
                _CorSet = MyBase.CreateObjectSet(Of Cor)("CorSet")
            End If
            Return _CorSet
        End Get
    End Property

    Private _CorSet As ObjectSet(Of Cor)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ProdutoTamanhoSet() As ObjectSet(Of ProdutoTamanho)
        Get
            If (_ProdutoTamanhoSet Is Nothing) Then
                _ProdutoTamanhoSet = MyBase.CreateObjectSet(Of ProdutoTamanho)("ProdutoTamanhoSet")
            End If
            Return _ProdutoTamanhoSet
        End Get
    End Property

    Private _ProdutoTamanhoSet As ObjectSet(Of ProdutoTamanho)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the CategoriaSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCategoriaSet(ByVal categoria As Categoria)
        MyBase.AddObject("CategoriaSet", categoria)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ProdutoSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProdutoSet(ByVal produto As Produto)
        MyBase.AddObject("ProdutoSet", produto)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ProdutoCorSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProdutoCorSet(ByVal produtoCor As ProdutoCor)
        MyBase.AddObject("ProdutoCorSet", produtoCor)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the CorSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCorSet(ByVal cor As Cor)
        MyBase.AddObject("CorSet", cor)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ProdutoTamanhoSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProdutoTamanhoSet(ByVal produtoTamanho As ProdutoTamanho)
        MyBase.AddObject("ProdutoTamanhoSet", produtoTamanho)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Categoria")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Categoria
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Categoria object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="nome">Initial value of the Nome property.</param>
    Public Shared Function CreateCategoria(id As Global.System.Int32, nome As Global.System.String) As Categoria
        Dim categoria as Categoria = New Categoria
        categoria.Id = id
        categoria.Nome = nome
        Return categoria
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Nome() As Global.System.String
        Get
            Return _Nome
        End Get
        Set
            OnNomeChanging(value)
            ReportPropertyChanging("Nome")
            _Nome = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Nome")
            OnNomeChanged()
        End Set
    End Property

    Private _Nome As Global.System.String
    Private Partial Sub OnNomeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNomeChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Model", "CategoriaProduto", "Produto")>
     Public Property Produto() As EntityCollection(Of Produto)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Produto)("Model.CategoriaProduto", "Produto")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Produto)("Model.CategoriaProduto", "Produto", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Cor")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Cor
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Cor object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="nome">Initial value of the Nome property.</param>
    Public Shared Function CreateCor(id As Global.System.Int32, nome As Global.System.String) As Cor
        Dim cor as Cor = New Cor
        cor.Id = id
        cor.Nome = nome
        Return cor
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Nome() As Global.System.String
        Get
            Return _Nome
        End Get
        Set
            OnNomeChanging(value)
            ReportPropertyChanging("Nome")
            _Nome = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Nome")
            OnNomeChanged()
        End Set
    End Property

    Private _Nome As Global.System.String
    Private Partial Sub OnNomeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNomeChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Model", "CorProdutoCor", "ProdutoCor")>
     Public Property ProdutoCor() As EntityCollection(Of ProdutoCor)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ProdutoCor)("Model.CorProdutoCor", "ProdutoCor")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ProdutoCor)("Model.CorProdutoCor", "ProdutoCor", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Produto")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Produto
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Produto object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="nome">Initial value of the Nome property.</param>
    ''' <param name="categoriaId">Initial value of the CategoriaId property.</param>
    ''' <param name="precoVenda">Initial value of the PrecoVenda property.</param>
    Public Shared Function CreateProduto(id As Global.System.Int32, nome As Global.System.String, categoriaId As Global.System.Int32, precoVenda As Global.System.Decimal) As Produto
        Dim produto as Produto = New Produto
        produto.Id = id
        produto.Nome = nome
        produto.CategoriaId = categoriaId
        produto.PrecoVenda = precoVenda
        Return produto
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Nome() As Global.System.String
        Get
            Return _Nome
        End Get
        Set
            OnNomeChanging(value)
            ReportPropertyChanging("Nome")
            _Nome = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Nome")
            OnNomeChanged()
        End Set
    End Property

    Private _Nome As Global.System.String
    Private Partial Sub OnNomeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNomeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CategoriaId() As Global.System.Int32
        Get
            Return _CategoriaId
        End Get
        Set
            OnCategoriaIdChanging(value)
            ReportPropertyChanging("CategoriaId")
            _CategoriaId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CategoriaId")
            OnCategoriaIdChanged()
        End Set
    End Property

    Private _CategoriaId As Global.System.Int32
    Private Partial Sub OnCategoriaIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCategoriaIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PrecoVenda() As Global.System.Decimal
        Get
            Return _PrecoVenda
        End Get
        Set
            OnPrecoVendaChanging(value)
            ReportPropertyChanging("PrecoVenda")
            _PrecoVenda = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PrecoVenda")
            OnPrecoVendaChanged()
        End Set
    End Property

    Private _PrecoVenda As Global.System.Decimal
    Private Partial Sub OnPrecoVendaChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnPrecoVendaChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Model", "CategoriaProduto", "Categoria")>
    Public Property Categoria() As Categoria
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Categoria)("Model.CategoriaProduto", "Categoria").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Categoria)("Model.CategoriaProduto", "Categoria").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CategoriaReference() As EntityReference(Of Categoria)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Categoria)("Model.CategoriaProduto", "Categoria")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Categoria)("Model.CategoriaProduto", "Categoria", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Model", "ProdutoProdutoCor", "ProdutoCor")>
     Public Property ProdutoCor() As EntityCollection(Of ProdutoCor)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ProdutoCor)("Model.ProdutoProdutoCor", "ProdutoCor")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ProdutoCor)("Model.ProdutoProdutoCor", "ProdutoCor", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Model", Name:="ProdutoCor")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ProdutoCor
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ProdutoCor object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="produtoId">Initial value of the ProdutoId property.</param>
    ''' <param name="corId">Initial value of the CorId property.</param>
    Public Shared Function CreateProdutoCor(id As Global.System.Int32, produtoId As Global.System.Int32, corId As Global.System.Int32) As ProdutoCor
        Dim produtoCor as ProdutoCor = New ProdutoCor
        produtoCor.Id = id
        produtoCor.ProdutoId = produtoId
        produtoCor.CorId = corId
        Return produtoCor
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProdutoId() As Global.System.Int32
        Get
            Return _ProdutoId
        End Get
        Set
            OnProdutoIdChanging(value)
            ReportPropertyChanging("ProdutoId")
            _ProdutoId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ProdutoId")
            OnProdutoIdChanged()
        End Set
    End Property

    Private _ProdutoId As Global.System.Int32
    Private Partial Sub OnProdutoIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnProdutoIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CorId() As Global.System.Int32
        Get
            Return _CorId
        End Get
        Set
            OnCorIdChanging(value)
            ReportPropertyChanging("CorId")
            _CorId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CorId")
            OnCorIdChanged()
        End Set
    End Property

    Private _CorId As Global.System.Int32
    Private Partial Sub OnCorIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCorIdChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Model", "ProdutoProdutoCor", "Produto")>
    Public Property Produto() As Produto
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Produto)("Model.ProdutoProdutoCor", "Produto").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Produto)("Model.ProdutoProdutoCor", "Produto").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ProdutoReference() As EntityReference(Of Produto)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Produto)("Model.ProdutoProdutoCor", "Produto")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Produto)("Model.ProdutoProdutoCor", "Produto", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Model", "ProdutoCorProdutoTamanho", "ProdutoTamanho")>
     Public Property ProdutoTamanho() As EntityCollection(Of ProdutoTamanho)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ProdutoTamanho)("Model.ProdutoCorProdutoTamanho", "ProdutoTamanho")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ProdutoTamanho)("Model.ProdutoCorProdutoTamanho", "ProdutoTamanho", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Model", "CorProdutoCor", "Cor")>
    Public Property Cor() As Cor
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cor)("Model.CorProdutoCor", "Cor").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cor)("Model.CorProdutoCor", "Cor").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CorReference() As EntityReference(Of Cor)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cor)("Model.CorProdutoCor", "Cor")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Cor)("Model.CorProdutoCor", "Cor", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Model", Name:="ProdutoTamanho")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ProdutoTamanho
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ProdutoTamanho object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="tamanho">Initial value of the Tamanho property.</param>
    ''' <param name="estoqueCorrente">Initial value of the EstoqueCorrente property.</param>
    ''' <param name="produtoCorId">Initial value of the ProdutoCorId property.</param>
    Public Shared Function CreateProdutoTamanho(id As Global.System.Int32, tamanho As Global.System.Int16, estoqueCorrente As Global.System.Int16, produtoCorId As Global.System.Int32) As ProdutoTamanho
        Dim produtoTamanho as ProdutoTamanho = New ProdutoTamanho
        produtoTamanho.Id = id
        produtoTamanho.Tamanho = tamanho
        produtoTamanho.EstoqueCorrente = estoqueCorrente
        produtoTamanho.ProdutoCorId = produtoCorId
        Return produtoTamanho
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Tamanho() As Global.System.Int16
        Get
            Return _Tamanho
        End Get
        Set
            OnTamanhoChanging(value)
            ReportPropertyChanging("Tamanho")
            _Tamanho = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Tamanho")
            OnTamanhoChanged()
        End Set
    End Property

    Private _Tamanho As Global.System.Int16
    Private Partial Sub OnTamanhoChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnTamanhoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property EstoqueCorrente() As Global.System.Int16
        Get
            Return _EstoqueCorrente
        End Get
        Set
            OnEstoqueCorrenteChanging(value)
            ReportPropertyChanging("EstoqueCorrente")
            _EstoqueCorrente = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EstoqueCorrente")
            OnEstoqueCorrenteChanged()
        End Set
    End Property

    Private _EstoqueCorrente As Global.System.Int16
    Private Partial Sub OnEstoqueCorrenteChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnEstoqueCorrenteChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProdutoCorId() As Global.System.Int32
        Get
            Return _ProdutoCorId
        End Get
        Set
            OnProdutoCorIdChanging(value)
            ReportPropertyChanging("ProdutoCorId")
            _ProdutoCorId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ProdutoCorId")
            OnProdutoCorIdChanged()
        End Set
    End Property

    Private _ProdutoCorId As Global.System.Int32
    Private Partial Sub OnProdutoCorIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnProdutoCorIdChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Model", "ProdutoCorProdutoTamanho", "ProdutoCor")>
    Public Property ProdutoCor() As ProdutoCor
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ProdutoCor)("Model.ProdutoCorProdutoTamanho", "ProdutoCor").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ProdutoCor)("Model.ProdutoCorProdutoTamanho", "ProdutoCor").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ProdutoCorReference() As EntityReference(Of ProdutoCor)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of ProdutoCor)("Model.ProdutoCorProdutoTamanho", "ProdutoCor")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of ProdutoCor)("Model.ProdutoCorProdutoTamanho", "ProdutoCor", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

